### ISSUE TITLE
Sybase Support

### ISSUE THREAD

**Issue by atifaziz** [elmah/Elmah#125]
How about sybase support?

If you are interested, here are the file for Sybase IAnywhere.

---
Originally reported on Google Code with ID 125

Reported by @cbrandsma-cs on 2009-06-29 21:10:15

<hr>
 * *Attachment: [IAnywhere.zip](https://storage.googleapis.com/google-code-attachments/elmah/issue-125/comment-0/IAnywhere.zip)*

**Comment by cbrandsma-cs** [comment]
Now there is something I have not thought about in a very long time.

**Comment by atifaziz** [comment]
@cbrandsma-cs See, you were not forgotten. :wink: I've always left this issue open so anyone wanting to add Sybase support would be able to search, find and start with [the attachment](https://storage.googleapis.com/google-code-attachments/elmah/issue-125/comment-0/IAnywhere.zip). However since no one's picked up the lead on this, I'm considering it stale and closing the issue. In any event, the simpler way of going about this today would be to share via a separate GitHub repo and publish on NuGet.
