### ISSUE TITLE
Use XML Data Type instead of NTEXT on SQL Server

### ISSUE THREAD

**Issue by atifaziz** [elmah/Elmah#265]
Use the `XML` data type instead of `NTEXT` with SQL Server.

The `XML` data type allows usage of XQuery to query the XML itself.  This can typically be used to extract columns of data from XML nodes for filtering, reporting, etc, and has the potential to be used in computed columns as well.

See the [XQuery language reference](http://msdn.microsoft.com/en-us/library/ms189075.aspx) for more information.

---
Originally reported on Google Code with ID 265

Reported by `msumerano` on 2012-01-06 04:07:17

**Comment by DancesWithBamboo** [comment]
NTEXT is now deprecated on Sql Server 2016/17 and most likely won't be available in the next release.  Whether or not to change to XML can be debated; but it's either that or varchar(max) very soon.

**Comment by atifaziz** [comment]
This issue was moved to elmah/SqlErrorLog#1
