### ISSUE TITLE
How to log to database and have the Logged event fired

### ISSUE THREAD

**Issue by atifaziz** [elmah/Elmah#300]
Hi,

Problem: How to log to the database and also have the `ErrorLog_Logged` event to fire?

## What steps will reproduce the problem?

1. add `<errorLog type="Elmah.SqlErrorLog, Elmah" connectionStringName="connNameCommon"
/>` to the `<elmah>` tag
2. Then in `global.asax` the event `ErrorLog_Logged` stops firing.
3. Once I remove `<errorLog type="Elmah.SqlErrorLog, Elmah" connectionStringName="connNameCommon" />`, then `ErrorLog_Logged` fires again.

## What is the expected output?

I expect to log to the database and also have the `ErrorLog_Logged` event to fire.

I have attached my `global.asax` and `web.config` files.

Thank you,
-Tesh

---
Attachments:

- [`Global.asax`](https://storage.googleapis.com/google-code-attachments/elmah/issue-300/comment-0/Global.asax)
- [`Web.config`](https://storage.googleapis.com/google-code-attachments/elmah/issue-300/comment-0/Web.config)

---
Originally reported on Google Code with ID 300

Reported by `always90s` on 2012-07-11 15:42:43

**Comment by ThomasArdal** [comment]
I just tested this and everything seems to work fine. I did actually experience this behavior in my initial test, but that was caused by a wrong connection string in my config. In my head, it makes sense, that the `ErrorLog_Logged` method isn't called, if the SQL logger cannot log the error.

Maybe just close this one, since the feature looks to work as it should?

**Comment by atifaziz** [comment]
Thanks @ThomasArdal. I think you're right. The connection string `connNameCommon` isn't defined in the `web.config` so I'm assuming that was the source of the problem. It starts firing again in step 3 because the default memory-based `ErrorLog` implementation kicks in.

**Comment by ThomasArdal** [comment]
I didn't get that deep into the original files. Well spotted! It's definitely the problem.
