### ISSUE TITLE
Documentation on compiling is out of date

### ISSUE THREAD

**Issue by atifaziz** [elmah/Elmah#352]
The [Compiling](https://elmah.github.io/a/compiling/) wiki page is out of date. It states that Visual Studio solutions are available in a directory that no longer exists in the source tree (`src/Solutions`), and lists as the latest supported version Visual Studio 2010, when the only solution now in the source tree is in the Visual Studio 2012 format.

---
Originally reported on Google Code with ID 352

Reported by `yoni@kallay.net` on 2014-02-28 19:34:06

**Comment by ThomasArdal** [comment]
If you assign me, I'll fix this one :smile:

**Comment by atifaziz** [comment]
Migrated to elmah/www#28.

@ThomasArdal Thanks and assigned the migrated issue to you.
