### ISSUE TITLE
Move repo/project off Google Code

### ISSUE THREAD

**Issue by atifaziz** [elmah/Elmah#391]
One of the official owners of this project should move this over to GitHub before it is lost.  It will be better for the project.

---
Originally reported on Google Code with ID 391
Reported by @issafram on 2015-05-14 13:20:12

**Comment by kenwarner** [comment]
:+1:

**Comment by issafram** [comment]
So you just decide to move issues only?

**Comment by atifaziz** [comment]
@issafram Yes, I decided to move only the issues to GitHub at the moment as the [export tool](https://code.google.com/p/support-tools/wiki/IssueExporterTool) provided a reasonable transition with least problems. The code has a more complex history & state right now with several forks in flight so may migrate to GitHub over time but do take note of the title of this issue: “Move repo/project off Google Code” (thoughtfully provided by you). It doesn't say anything about putting all your eggs in the GitHub basket, so that's just an opinion. :smile:

The first item of order was to find a new home for all the project assets (code, issue tracker, downloads & wikis) before the Google Code projects go read-only (which happened yesterday) and that's been done. As of this comment, the new homes are:

* [Hg repos @ BitBucket](https://bitbucket.org/project-elmah/)
* [Project site and wikis](https://elmah.github.io/) @ [elmah/www on GitHub](https://github.com/elmah/www)
* [Issue tracker](https://github.com/elmah/Elmah/issues) over [here](https://github.com/elmah/Elmah/issues)
* [Old SVN repo @ Assembla](https://www.assembla.com/spaces/elmah/subversion/source)

While it may appear fragmented, some of the [latest developments in ELMAH are happening on GitHub](https://github.com/elmah/Bootstrapper). See the [Bootstrapper](https://github.com/elmah/Bootstrapper) project.

**Comment by atifaziz** [comment]
Closing this issue as all project assets have been moved off Google Code.

**Comment by akasarto** [comment]
Hey. Sorry for bringing this up again, but I'm confused about which one is the official repository. On this thread you mention bitbucket (that I was unaware until now), but the source code here on github was recently changed as well. Is this the official repository or is the one on bitbucket (project-elmah)? I coudn't find anything like 'this repository was moved to...' anywhere.

**Comment by atifaziz** [comment]
@akasarto This issue was about getting it off Google Code Project Hosting and that was done. The issues were migrated here while the code was moved to BitBucket since that offered Mercurial and required the least effort in terms of code migration. #400 as a second step migrated the code from Mercurial to Git and finally hosted together with the issues here so this is the official repo. I can understand the confusion but the project has a long history & assets had to be rescued more than once (GotDotNet, then Google Code). Some links may still refer to BitBucket but that may be just some downloads & pointers into the source code when it was under Mercurial as a source code control system.

**Comment by ThomasArdal** [comment]
:+1:

**Comment by akasarto** [comment]
Cool! Thanks for the quick response.
