### ISSUE TITLE
Log to REST-based service

### ISSUE THREAD

**Issue by atifaziz** [elmah/Elmah#395]
Rather than logging to a centralized database, ELMAH could send a JSON-serialized exception to a user-specified endpoint to allow centralized exception logging. This would remove the need for a persistent DB connections.

This is _NOT_ a request for an endpoint, just the ability to supply our own endpoint.

---

Originally reported on Google Code with ID 395

Reported by `andlewis` on 2015-07-06 20:10:32

**Comment by ThomasArdal** [comment]
Maybe just close this one? As you say, `ErrorPostModule` does exactly this.

**Comment by atifaziz** [comment]
Duplicate of #359
