### ISSUE TITLE
Update project site reference in the Nuget package

### ISSUE THREAD

**Issue by tiesont** [elmah/Elmah#404]
Would it be possible to update the version 1.2.2 package's project link? It still points to the Google Code repo. This can be done within the nuget.org website, so a package update is not required.

On the outside chance it helps:

1. Select "Manage my Packages" (https://www.nuget.org/account/Packages) from the account screen.
2. Select the package from your list.
3. Select "Edit package" (left sidebar, under the project stats).
4. Update the "Project Home Page URL" field.

This will update the Project Information link shown in the package explorer, and on the website.

---

- [x] [`elmah`](https://www.nuget.org/packages/elmah)
- [x] [`elmah.corelibrary`](https://www.nuget.org/packages/elmah.corelibrary)
- [x] [`elmah.filtering.sample`](https://www.nuget.org/packages/elmah.filtering.sample)
- [x] [`elmah.msaccess`](https://www.nuget.org/packages/elmah.msaccess)
- [x] [`elmah.mysql`](https://www.nuget.org/packages/elmah.mysql)
- [x] [`elmah.oracle`](https://www.nuget.org/packages/elmah.oracle)
- [x] [`elmah.postgresql`](https://www.nuget.org/packages/elmah.postgresql)
- [x] [`elmah.sqlserver`](https://www.nuget.org/packages/elmah.sqlserver)
- [x] [`elmah.sqlservercompact`](https://www.nuget.org/packages/elmah.sqlservercompact)
- [x] [`elmah.xml`](https://www.nuget.org/packages/elmah.xml)

**Comment by atifaziz** [comment]
Tracking for all currently published packages:

- [x] [`elmah`](https://www.nuget.org/packages/elmah/elmah)
- [x] [`elmah.corelibrary`](https://www.nuget.org/packages/elmah/elmah.corelibrary)
- [ ] [`elmah.filtering.sample`](https://www.nuget.org/packages/elmah/elmah.filtering.sample)
- [ ] [`elmah.msaccess`](https://www.nuget.org/packages/elmah/elmah.msaccess)
- [ ] [`elmah.mysql`](https://www.nuget.org/packages/elmah/elmah.mysql)
- [ ] [`elmah.oracle`](https://www.nuget.org/packages/elmah/elmah.oracle)
- [ ] [`elmah.postgresql`](https://www.nuget.org/packages/elmah/elmah.postgresql)
- [ ] [`elmah.sqlite`](https://www.nuget.org/packages/elmah/elmah.sqlite)
- [ ] [`elmah.sqlserver`](https://www.nuget.org/packages/elmah/elmah.sqlserver)
- [ ] [`elmah.sqlservercompact`](https://www.nuget.org/packages/elmah/elmah.sqlservercompact)
- [ ] [`elmah.xml`](https://www.nuget.org/packages/elmah/elmah.xml)

**Comment by atifaziz** [comment]
@tiesont Thanks for the detailed instructions. 😃

**Comment by tiesont** [comment]
@atifaziz No problem. I honestly wasn't expecting such a quick response, so it should probably be *me* thanking *you*. :)

**Comment by atifaziz** [comment]
@tiesont Drop a line when you can see the [changes for the first 2 packages](https://github.com/elmah/Elmah/issues/404#issuecomment-235732505).

**Comment by tiesont** [comment]
I see the changes on the site. I had to uninstall and reinstall the elmah.corelibrary package to see the updated reference in the package explorer (clearing the package cache didn't seem to help), but that seems good to go too. Not sure why the elmah package isn't updating.

Interestingly enough, I see the old link when looking at installed packages, but the new link when looking at available (online) packages. I assume this is just stale data in the NuGet API.

Thanks, again. :)

**Comment by atifaziz** [comment]
Done for:

- [`elmah.msaccess`](https://www.nuget.org/packages/elmah.msaccess)
- [`elmah.xml`](https://www.nuget.org/packages/elmah.xml)

**Comment by atifaziz** [comment]
Done for rest:

- [`elmah.filtering.sample`](https://www.nuget.org/packages/elmah.filtering.sample)
- [`elmah.mysql`](https://www.nuget.org/packages/elmah.mysql)
- [`elmah.oracle`](https://www.nuget.org/packages/elmah.oracle)
- [`elmah.postgresql`](https://www.nuget.org/packages/elmah.postgresql)
- [`elmah.sqlserver`](https://www.nuget.org/packages/elmah.sqlserver)
- [`elmah.sqlservercompact`](https://www.nuget.org/packages/elmah.sqlservercompact)
