### ISSUE TITLE
Reg: Elmah not writing files in remote access

### ISSUE THREAD

**Issue by seshusakinala** [elmah/Elmah#406]
I have deployed and configured Elmah application to allow remote access. I am able to access remote but the application is not writing any log files in App_Data folder and the thing is i can access the ...ElmahExample/elmah.axd url.

 ( ie, if any file available in App_Data i can read that but new logs are not writing. folder is having read and write permissions)

**Comment by atifaziz** [comment]
You say ELMAH is “not writing files in remote access” but is it writing them when you forbid remote access?

> if any file available in App_Data i can read 

How are you reading it?

> folder is having read and write permissions

For which identity? The same under which the web app is running?

**Comment by atifaziz** [comment]
Closing for now due to lack of response.
