### ISSUE TITLE
Mysql MyIsam vs InnoDb

### ISSUE THREAD

**Issue by mika76** [elmah/Elmah#410]
Is there any specific reason that the mysql script creates the elmah_error as a MyIsam table? Every time my computer crashes I need to repair the db. InnoDb is a superior engine in many way. So basically my question is, is there a specific reason it is MyIsam or could that be changed?

**Comment by atifaziz** [comment]
I don't know much about MySQL but @nberardi, who is the original contributor/maintainer of `MySqlErrorLog`, would be in the best position to answer your question.

**Comment by mika76** [comment]
I have changed it in my db to InnoDb and am not seeing any problems. MyIsam is maybe a little faster on reads but I would think Elmah is more write dependant and innodb supports a whole bunch more stuff than MyIsam and it is now (for a couple of years now) the default mysql table engine.

**Comment by atifaziz** [comment]
> Elmah is more write dependant

That'd be the case for an app generating lots of errors.

I imagine your free to change the script to use the InnoDB engine if it suits you better.

**Comment by mika76** [comment]
Yeah I already have. I was just wondering if I was missing something...

**Comment by atifaziz** [comment]
> I was just wondering if I was missing something...

As I said, I can't comment on this but if @nberardi is listening then let's hope he'll drop by with his 2&cent; in future not too distant. Meanwhile, I'm going to close this as we haven't heard anything in 2 weeks.
