### ISSUE TITLE
nuget elmah.mysql has dependency on whole Elmah instead of Elmah.core

### ISSUE THREAD

**Issue by mika76** [elmah/Elmah#411]
Could this be changed? There is no reason to install the SQL server bingings if mysql is being used. And all the othe nuget's for elmas addons use elmah.core...

**Comment by atifaziz** [comment]
> There is no reason to install the SQL server bindings

That shouldn't be happening. The `elmah` package configures the handler and modules in your `web.config` in addition to installing the core library.

> all the othe nuget's for elmas addons use elmah.core

I don't see that. For example the [`elmah.sqlserver` package depends on the `elmah` package](https://github.com/elmah/Elmah/blob/1657d27db8d4ce1f0e90c227907526c4071b84c5/nuget/Elmah.SqlServer.nuspec#L18), [as does `elmah.oracle`](https://github.com/elmah/Elmah/blob/1657d27db8d4ce1f0e90c227907526c4071b84c5/nuget/Elmah.Oracle.nuspec#L18) [and `elmah.xml`](https://github.com/elmah/Elmah/blob/1657d27db8d4ce1f0e90c227907526c4071b84c5/nuget/Elmah.Xml.nuspec#L18).

**Comment by atifaziz** [comment]
Closing as stale.
