### ISSUE TITLE
Error filter with custom Exception class doesn't work

### ISSUE THREAD

**Issue by phillijw** [elmah/Elmah#414]
We have a custom exception class called `ModelValidationException`. For some reason the filter is not keeping the exception from being propagated via email and other forms of logging. The app does not crash while loading because it does seem to recognize the type. The filter does work properly with a regular type such as `System.Exception`.

```
<errorFilter>
      <test>
        <not>
          <is-type binding="Exception" type="MEDIC.Web.ModelValidationException, MEDIC.Web" />
        </not>
      </test>
</errorFilter> 
```

When moving this filter into code (method #2 from http://www.diaryofaninja.com/blog/2011/09/20/adding-filters-to-your-elmah-installation), inside the Global.asax, it works fine.

**Comment by atifaziz** [comment]
I think you might have the condition inverted due to the `<not>`. Try with just:

```xml
<errorFilter>
    <test>
        <is-type binding="Exception" type="MEDIC.Web.ModelValidationException, MEDIC.Web" />
    </test>
</errorFilter> 
```

Does it help?
