### ISSUE TITLE
Upgrading to Sql 2016

### ISSUE THREAD

**Issue by JKetter** [elmah/Elmah#421]
With the upgrade to Sql 2016 the 'XML Auto' is not longer supported. The query ELMAH_GetErrorsXml contains the 'XML Auto'..... is there a replacement for this query? My database team s insisting on removing the XML Auto from the query.

**Comment by atifaziz** [comment]
@JKetter I just checked the following topics in the SQL Server documentation and I don't see any mention of `XML AUTO` being no longer supported:

- [Deprecated Database Engine Features in SQL Server 2016](https://docs.microsoft.com/en-us/sql/database-engine/deprecated-database-engine-features-in-sql-server-2016)
- [Discontinued Database Engine Functionality in SQL Server 2016](https://docs.microsoft.com/en-us/sql/database-engine/discontinued-database-engine-functionality-in-sql-server-2016)
- [Breaking Changes to Database Engine Features in SQL Server 2016](https://docs.microsoft.com/en-us/sql/database-engine/breaking-changes-to-database-engine-features-in-sql-server-2016)
- [Use `AUTO` Mode with `FOR XML`](https://docs.microsoft.com/en-us/sql/relational-databases/xml/use-auto-mode-with-for-xml)
- [`FOR XML` (SQL Server)](https://docs.microsoft.com/en-us/sql/relational-databases/xml/for-xml-sql-server)

Do you have a link to some official article that quotes the non-support?

**Comment by JKetter** [comment]
Thank you for the information. I also could not find anything from the official MS documentation on XML Auto going away. We have one of MS top experts in SQL here in the office and she reported out that the queries using XML Auto need to be re-worked prior to out upgrade to Sql 2016.... I'll push back pointing out the MS documentation and see where that get me. Thanks again.

**Comment by atifaziz** [comment]
@JKetter I'll go ahead and close this for now. If you find out more after talking to the expert then we can revisit the issue.
