### ISSUE TITLE
Index not found error while retrieving stylesheet

### ISSUE THREAD

**Issue by aibars** [elmah/Elmah#423]
Hi,

After certain deploys to an Azure App Service, I receive the following error when Elmah tries to retrieve the stylesheet:

```
[BadImageFormatException: Index not found. (Exception from HRESULT: 0x80131124)]
   Elmah.ManifestResourceHandler.ProcessRequest(HttpContext context) +0
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +559
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +70
```

The URL is `~/elmah.axd/stylesheet`

Unfortunately, this seems to happen randomly and therefore I cannot reproduce the issue properly.
Could you give me a lead on what could be wrong with my Web API project?

Thanks

**Comment by atifaziz** [comment]
Googling around for “[BadImageFormatException+"Index+not+found"](https://www.google.com/search?q=BadImageFormatException+"Index+not+found")”, it seems this isn't really related specifically to ELMAH. I would suggest checking with the Azure support.
