### ISSUE TITLE
Transfer ErrorLog implementations to their respective authors

### ISSUE THREAD

**Issue by atifaziz** [elmah/Elmah#428]
@erikej @JamesDriscoll @laimis @nberardi @simoneb Thank you for your various `ErrorLog` implementations over the years that have been part of ELMAH proper. In PR #424 for #418, the implementations were split into their own repos. The rationale laid out in #418 was:

> ELMAH 1.x shipped with a number of `ErrorLog` implementations built-in. This had the simplicity and advantage of shipping and deploying a single assembly in production. However, it required everything to be managed and released as a single unit and this made coordinating between the various `ErrorLog` authors/contributors difficult. Moreover some of the authors don't appear to be actively maintaining their implementations anymore. Going forward, the `ErrorLog` implementations will be split into separate repositories so that each can have its own issue tracking, release management, evolution and ownership.

I have done all the work necessary to make the split as simple as possible, set-up the repos (see below) and adjust the `.nuspec` files. I'd like to now transfer the ownership of your implementation repo(s) over to you. In case you're wondering, this requires no further commitment on your end whatsoever, especially if you've moved on to other projects, platforms or interests and have no motivation in maintaining your contribution. At the very least, it'll appear on your GitHub profile as part of your legacy 🏅 and you are free to transfer it to someone else who may be interested in picking up after you.

The following repos will be transferred to their respective authors:

| Owner          | Error Log Implementation/Repo                                                 |
|----------------|-------------------------------------------------------------------------------|
| @JamesDriscoll | [AccessErrorLog](https://github.com/elmah/AccessErrorLog)                     |
| @nberardi      | [MySqlErrorLog](https://github.com/elmah/MySqlErrorLog)                       |
| @JamesDriscoll | [OracleErrorLog](https://github.com/elmah/OracleErrorLog)                     |
| @laimis        | [PgsqlErrorLog](https://github.com/elmah/PgsqlErrorLog)                       |
| @simoneb       | [SQLiteErrorLog](https://github.com/elmah/SQLiteErrorLog)                     |
| @atifaziz      | [SqlErrorLog](https://github.com/elmah/SqlErrorLog)                           |
| @erikej        | [SqlServerCompactErrorLog](https://github.com/elmah/SqlServerCompactErrorLog) |

Each repo is setup such that it depends on [ELMAH 2.0 alpha](https://www.nuget.org/packages/elmah.corelibrary/2.0.0-alpha001) right now. There is currently no plan or release date for ELMAH 2.0 but this split should help move in that direction.

If you have any questions, don't hesitate to ask.

## Status

- [x] [AccessErrorLog](https://github.com/elmah/AccessErrorLog)
- [x] [MySqlErrorLog](https://github.com/elmah/MySqlErrorLog)
- [x] [OracleErrorLog](https://github.com/elmah/OracleErrorLog)
- [x] [PgsqlErrorLog](https://github.com/elmah/PgsqlErrorLog)
- [x] [SQLiteErrorLog](https://github.com/elmah/SQLiteErrorLog)
- [x] [SqlServerCompactErrorLog](https://github.com/elmah/SqlServerCompactErrorLog)

**Comment by atifaziz** [comment]
@ErikEJ @JamesDriscoll @laimis @nberardi @simoneb You have all been added as administrators of your repo.

**Comment by atifaziz** [comment]
@ErikEJ @JamesDriscoll @laimis @nberardi @simoneb Thanks for accepting the invitation to become administrators of your contribution's repo. If you wish to have the repo transferred to your profile then just drop in a line here and I'll initiate the process. If you don't want to maintain the repo going forward but want to leave it under the @elmah org then that's fine but I'd like to suggest adding a note to [the repo description](https://stackoverflow.com/a/21649064/6682) along the lines of:

> 📢 Seeking new maintainer(s)

You can also set a website URL at the same time, which I would set to the URL of an issue in your repo that also reads “Seeking new maintainer(s)” as the subject.

**Comment by JamesDriscoll** [comment]
Hi Atif,
I'll take mine over :O)
Cheers,
James

**Comment by atifaziz** [comment]
@JamesDriscoll Per GitHub, this has to be done as a two-step process: I have to transfer to my profile first before transferring to yours. I've done that for [AccessErrorLog](https://github.com/elmah/AccessErrorLog) so let me know when the transfer is complete. If all goes well, I'll proceed the same way with [OracleErrorLog](https://github.com/elmah/OracleErrorLog).

**Comment by JamesDriscoll** [comment]
Hi Atif,
The AccessErrorLog transfer went successfully.However, I was able to transfer OracleErrorLog directly to me as I'm part of the ELMAH organization!! :O)
Cheers,
James

**Comment by JamesDriscoll** [comment]
FYI
I have also renamed my repositories so that they make more sense outside the ELMAH organisation.
I now have:
https://github.com/JamesDriscoll/ELMAH.AccessErrorLog
https://github.com/JamesDriscoll/ELMAH.OracleErrorLog

Cheers,
James

**Comment by paal123** [comment]
For me it is bit of a problem that the OracleErrorLog is no longer a part of the official Elmh repo and has no nuget package, as my customer, a large multinational company requests me to use official Elmah nuget packages. I can be an official maintainer as we need this for long term usage with Oracle Managed Driver.

**Comment by atifaziz** [comment]
@paal123 Thanks for stepping up to volunteer and help maintain OracleErrorLog. While I'll let @JamesDriscoll answer on how he sees the collaboration going forward, I wanted to point out that what's in the [ELMAH.OracleErrorLog](https://github.com/JamesDriscoll/ELMAH.OracleErrorLog) repo is based on the [ELMAH 2.0 code that's currently “alpha”](https://www.nuget.org/packages/elmah.corelibrary/2.0.0-alpha001). Is your hope to get the managed version out based on 1.x (which by the way sits in [the `1x` branch](https://github.com/elmah/Elmah/tree/1x) here)?

**Comment by paal123** [comment]
I did make a working version of 1x with Oracle managed driver. My thought was elmah 2.0 nuget with an official OracleErrorLog nuget package in addition.

**Comment by atifaziz** [comment]
> I did make a working version of 1x with Oracle managed driver. 

@paal123 If you have a working version, why not start by sharing this as a repo under your account that we can eventually talk about transferring under the org? If it makes sense, you could fork [ELMAH.OracleErrorLog](https://github.com/JamesDriscoll/ELMAH.OracleErrorLog) and work your changes on top.

> My thought was elmah 2.0 nuget with an official OracleErrorLog nuget package in addition.

It might be best to publish an initial version still based on 1.x as 2.0 is still alpha.

**Comment by JamesDriscoll** [comment]
Hi guys,

Sorry for my silence 'til now!

Firstly, I have no issue with the repo sitting under the ELMAH organisation, or any other location. The important thing is to do the correct thing for ELMAH itself.

Second, I think we need to be a little bit careful in how the move to Oracle.ManagedDataAccess is implemented. As far as I'm aware, the Oracle managed client is ONLY available for .NET 4.0 and above. There will be folks out there who are still supporting .NET 3.5 SP1 and below, for which the current OracleErrorLog will be their only option. My initial feeling here is that we should have a brand new OracleManagedErrorLog that takes dependencies on Elmah.Core and Oracle.ManagedDataAccess.

Cheers,

James

**Comment by atifaziz** [comment]
@JamesDriscoll, @paal123: I think it would be best to continue this discussion as an issue for the [ELMAH.OracleErrorLog](ELMAH.OracleErrorLog) repo.
