### ISSUE TITLE
Log Page “Powered by” footer points to non-existent elmah.googlecode.com

### ISSUE THREAD

**Issue by tiggronline** [elmah/Elmah#431]
The link at the footer of the ELMAH.AXD page is still pointing at http://elmah.googlecode.com/, which gives a 404 Not Found if followed.

**Comment by atifaziz** [comment]
This [has been addressed in the code base to become 2.0](https://github.com/elmah/Elmah/blob/24aa8bb9aac684fe1a5fa8afe22ae19b7a2e3f57/src/Elmah.AspNet/PoweredBy.cshtml#L15). At this point, there's no plan to make a 1.x patch release so I am going to close this but thanks for taking the time to report the issue nonetheless.
